--- Original Author(s) : NLTP_ASHES
--- Edited : N/A
--- Date : 21/03/2023
--- License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)
---
--- Script used to manage the fake space restrictors used in the Western Goods addon.

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

local dbg_printf = western_goods_utils.dbg_printf

-- ---------------------------------------------------------------------------------------------------------------------
-- Functions
-- ---------------------------------------------------------------------------------------------------------------------

function in_bounds(who,data)
	if not who then
		printf("![WG] ERROR | Fake Restrictor | in_bounds() called with no game object !")
		return false
	elseif not data then
		printf("![WG] ERROR | Fake Restrictor | in_bounds() called with no restrictor data !")
		return false
	end

	local posx = who:position().x
	local posy = who:position().y
	local posz = who:position().z

	if (posx > data.ax) and (posz < data.az) and (posy > data.ay) and (posx < data.bx) and (posz > data.bz) and (posy < data.by) then
		dbg_printf("[WG] Fake Restrictor | %s in restrictor bounds", who:name())
		return true
	else
		return false
	end
end

function xr_conditions.in_bounds(enemy,npc,p)
	return in_bounds(enemy, { ax=p[1],ay=p[2],az=p[3],bx=p[4],by=p[5],bz=p[6] })
end